---
- name: 3. Instalar MySQL server
    apt:
      name: "{{ item }}"
    with_items:
      - python-mysqldb
      - mysql-server
      - mysql-client

- name: Start Mysql Service
    service: name=mysql state=started enabled=yes
	
- name: 6. Instalar PHPmyadmin
- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql_root_pass}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_root_pass}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{mysql_root_pass}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: install pma
  apt: pkg=phpmyadmin state=present

- name: configure site
  file: path=/var/www/phpmyadmin src=/usr/share/phpmyadmin state=link
	
- name: 10. Crear Base de Datos
    mysql_db: name=virtualboardphp state=present
	
- name: 11. Crear user y password para conectar a la base de datos
    mysql_user: name=virtualboard password=virtualboard priv=*.*:ALL state=present

- name: 12. Creacion de tabla
    command: sh ~/VirtualBoard/Aprovisionamiento/crearTabla.sh