
- hosts: virtualboard

  sudo: yes
  tasks:
  - name: 1. Instalar Apache
    apt: name=apache2 state=present

  - name: 2. Instalar PHP
    apt: name=libapache2-mod-php5 state=present

  - name: 3. Instalar MySQL server
    apt:
      name: "{{ item }}"
    with_items:
      - python-mysqldb
      - mysql-server
      - mysql-client

  - name: 5. Start Apache
    service: name=apache2 state=running enabled=yes

  - name: 6. Instalando git.
    apt: name=git state=present

  - name: 7. Clonando Repositorio desde git
    command: git clone  https://github.com/IV-2014/VirtualBoard.git

  - name: 8. Copiar php
    copy: src=../ServerConfiguration/PHP/src/ dest=/var/www/html mode=0644

  - name: 9. Crear Base de Datos
    mysql_db: name=virtualboardphp state=present
